//M101

#pragma once
#ifndef STATE_H
#define STATE_H

//STATI ORDINARI DEL SOFTWARE
#define STATE_INIT			0
#define STATE_PRELAUNCH		1
#define STATE_ASCENT		2
#define STATE_HIGH_DESCENT	3
#define STATE_TRANSITION	4
#define STATE_LOW_DESCENT	5
#define STATE_LANDED		6

//STATI NON ORDINARI DEL SOFTWARE
#define STATE_INTERRUPT		7
#define STATE_DISASTER		8
#define STATE_HIBERNATION	9

#endif
