//M101

#pragma once
#ifndef MISSION_H
#define MISSION_H

#define MISSIONE_APERTURA_PARACADUTE	300
#define MISSIONE_FREQUENZA_BASE			439000000
#define MISSIONE_FREQUENZA_STEP			25000
#define MISSIONE_FREQUENZA_UNIT			10

#endif
