//M101

#pragma once
#ifndef MISSION_H
#define MISSION_H

#define MISSIONE_APERTURA_PARACADUTE	0
#define MISSIONE_ATTIVAZIONE_BUZZER		0
#define MISSIONE_DELTA_AVVENUTO_LANCIO	1

#define SERVO_ANGOLO_APERTO 180
#define SERVO_ANGOLO_CHIUSO 0

#endif
